# Generated by Django 4.1.7 on 2023-04-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeMenu', '0003_alter_menuitem_parent_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_m', to='treeMenu.menu'),
        ),
    ]
